apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telegram-server.fullname" . }}-env
data:
  {{- range $key, $value := .Values.env }}
    {{ $key | quote  }}: {{ $value | quote }}
  {{- end }}
