apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "telegram-server.fullname" . }}-nginx-config
  labels:
    {{- include "telegram-server.labels" . | nindent 4 }}
data:
  nginx.conf: |-
{{ .Files.Get "configs/nginx.conf"  | indent 4 }}
  default.conf: |-
{{ .Files.Get "configs/default.conf"  | indent 4 }}