apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "telegram-server.fullname" . }}-secret"
  labels:
    environment: "{{ .Chart.Name }}"
    {{- include "telegram-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.envSecrets }}
    {{ $key | quote  }}: {{ $value | quote }}
  {{- end }}
