apiVersion: v1
kind: Service
metadata:
  name: {{ include "telegram-server.fullname" . }}-telegram
  labels:
    {{- include "telegram-server.labels" . | nindent 4 }}
    service: {{ include "telegram-server.fullname" . }}
spec:
  type: {{ .Values.service.nginx.type }}
  ports:
    - port: {{ .Values.service.telegram.port }}
      targetPort: 8081
      protocol: TCP
      name: telegram-server
  selector:
    {{- include "telegram-server.selectorLabels" . | nindent 4 }}
    service: {{ include "telegram-server.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "telegram-server.fullname" . }}-files
  labels:
    {{- include "telegram-server.labels" . | nindent 4 }}
    service: {{ include "telegram-server.fullname" . }}
spec:
  type: {{ .Values.service.nginx.type }}
  ports:
    - port: {{ .Values.service.nginx.port }}
      targetPort: 80
      protocol: TCP
      name: nginx
  selector:
    {{- include "telegram-server.selectorLabels" . | nindent 4 }}
    service: {{ include "telegram-server.fullname" . }}
---


