apiVersion: v1
kind: Service
metadata:
  name: {{ include "telegram-server.fullname" . }}
  labels:
    {{- include "telegram-server.labels" . | nindent 4 }}
    service: {{ include "telegram-server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: telegram-server
  selector:
    {{- include "telegram-server.selectorLabels" . | nindent 4 }}
    service: api

