name: Build and Deploy to Docker Registry

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Prepare environment
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | awk -F '/' '{print tolower($2)}')
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$REPO_NAME
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          load: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest

      - name: Get the version of the server and tag the image
        run: |
          version=$(docker run --rm ${{ env.IMAGE_NAME }}:latest --version 2>&1 | awk '{print $3}')
          echo $version
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:$version
          docker push ${{ env.IMAGE_NAME }}:$version
          docker push ${{ env.IMAGE_NAME }}:latest
