name: Build and Deploy to Docker Registry

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Prepare environment
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | awk -F '/' '{print tolower($2)}')
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$REPO_NAME
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest

      - name: Get the version of the server
        run: |
          version=$(docker run --quiet --rm ${{ env.IMAGE_NAME }}:latest --version 2>&1 | awk '{print $3}')
          echo "version=$version" >> $GITHUB_ENV

      - name: Tag the image
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:${{ env.version }}
          docker push ${{ env.IMAGE_NAME }}:${{ env.version }}
          
          MINOR_VERSION=$(echo ${{ env.version }} | cut -d. -f1,2)
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:$MINOR_VERSION
          docker push ${{ env.IMAGE_NAME }}:$MINOR_VERSION
          
          MAJOR_VERSION=$(echo ${{ env.version }} | cut -d. -f1)
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:$MAJOR_VERSION
          docker push ${{ env.IMAGE_NAME }}:$MAJOR_VERSION
